# Generated by Django 5.0.2 on 2024-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportage', '0002_reportage_dislikes_reportage_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportage',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
