# Generated by Django 5.0.2 on 2024-02-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('reportage', '0003_reportage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportage',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='reportages', to='category.category'),
        ),
    ]
